apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: neighborfit-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
      nodePort: 30080
